export const TOPICS = {
  js: {
    key: "js",
    file: "/js-prep/questions.json",
    label: "JavaScript",
    logoTitle: "JS Interview Prep",
    bmKey: "js-prep-bm",
    viewKey: "js-prep-viewed",
    defaultCat: "fundamentals",
    fallbackTotal: 478,
    categories: [
      {
        id: "fundamentals",
        icon: "🧱",
        title: "JavaScript Fundamentals",
        desc: "Core JS concepts — types, scope, closures, storage, and browser APIs.",
      },
      {
        id: "functions",
        icon: "🔧",
        title: "Functions & Scope",
        desc: "Currying, closures, higher-order patterns, generators, and async callbacks.",
      },
      {
        id: "objects",
        icon: "🏗️",
        title: "Objects & Prototypes",
        desc: "Prototypes, classes, Proxy, Reflect, Object internals, and inheritance.",
      },
      {
        id: "arrays",
        icon: "📦",
        title: "Arrays, Strings & Collections",
        desc: "Array/string methods, Set, Map, WeakMap, WeakSet, iterators.",
      },
      {
        id: "async",
        icon: "⚡",
        title: "Asynchronous JavaScript",
        desc: "Event loop, Promises, async/await, fetch, WebSockets and async patterns.",
      },
      {
        id: "dom",
        icon: "🌐",
        title: "DOM, Events & Browser",
        desc: "DOM manipulation, events, observers, browser APIs, security and performance.",
      },
      {
        id: "es6plus",
        icon: "🚀",
        title: "ES6+ & Modern JavaScript",
        desc: "Every modern JS feature from ES6 through ES2024 with practical examples.",
      },
      {
        id: "patterns",
        icon: "⚙️",
        title: "Patterns, Internals & Performance",
        desc: "Design patterns, V8 internals, performance, TypeScript, testing and tooling.",
      },
    ],
  },

  react: {
    key: "react",
    file: "/js-prep/react_questions.json",
    label: "React",
    logoTitle: "React Interview Prep",
    bmKey: "react-prep-bm",
    viewKey: "react-prep-viewed",
    defaultCat: "core",
    fallbackTotal: 318,
    categories: [
      {
        id: "core",
        icon: "⚛️",
        title: "Core React",
        desc: "JSX, components, state, props, events, Virtual DOM and reconciliation.",
      },
      {
        id: "hooks",
        icon: "🪝",
        title: "React Hooks",
        desc: "useState, useEffect, useRef, useCallback, useMemo, custom hooks and more.",
      },
      {
        id: "redux",
        icon: "🗂️",
        title: "React Redux",
        desc: "Actions, reducers, store, middleware, selectors and Redux Toolkit.",
      },
      {
        id: "router",
        icon: "🧭",
        title: "React Router",
        desc: "Client-side routing: history, params, navigation and protected routes.",
      },
      {
        id: "testing",
        icon: "🧪",
        title: "React Testing",
        desc: "Unit and integration testing with Jest and React Testing Library.",
      },
      {
        id: "misc",
        icon: "🔧",
        title: "Miscellaneous",
        desc: "Advanced patterns, performance, SSR, TypeScript and real-world usage.",
      },
      {
        id: "libraries",
        icon: "📦",
        title: "Libraries & Integration",
        desc: "Styled-components, Relay, Reselect and third-party integration.",
      },
      {
        id: "i18n",
        icon: "🌍",
        title: "Internationalization",
        desc: "Localizing React apps with i18n libraries, formatting and locale switching.",
      },
      {
        id: "native",
        icon: "📱",
        title: "React Native",
        desc: "Building mobile apps with React Native and platform-specific code.",
      },
    ],
  },
};
